# travis.yml

sudo: required
services:
  - docker

install:
  - docker build --pull -t 2stacks/docker-ovpn .

# Assist with ci test debugging:
#  - DEBUG=1

before_script:
  - image="2stacks/docker-ovpn"
  - docker inspect "$image"

script:
  - docker run -it --rm -v /$PWD/configs/ovpn:/etc/openvpn 2stacks/docker-ovpn gen-keys
  - docker run -itd -h openvpn --restart=always --name openvpn --cap-add=NET_ADMIN -e "RADIUS_HOST=freeradius" -e "RADIUS_KEY=testing123" -e "DNS_HOST1=1.1.1.1" -e "DNS_HOST2=1.0.0.1" -p 1194:1194/udp -p 443:443 -v /$PWD/configs/ovpn:/etc/openvpn 2stacks/docker-ovpn
  - docker container ls | grep openvpn

notifications:
  email:
    - 2stacks@2stacks.net